version: '3.8'

services:
  # 后端服务
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-hackathon-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 持久化上传文件
      - ./server/uploads:/app/uploads
      # 可选：挂载配置文件以便动态修改
      - ./server/configs/config.yaml:/app/configs/config.yaml:ro
    environment:
      - TZ=Asia/Shanghai
    networks:
      - ai-hackathon-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 前端服务
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ai-hackathon-web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    environment:
      - TZ=Asia/Shanghai
    networks:
      - ai-hackathon-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ai-hackathon-network:
    driver: bridge
