server:
  port: "8080"

qiniu:
  access_key: "your_qiniu_access_key"
  secret_key: "your_qiniu_secret_key"
  bucket: "your_bucket_name"

minio:
  endpoint: "${MINIO_ENDPOINT}"
  access_key: "${MINIO_ACCESS_KEY}"
  secret_key: "${MINIO_SECRET_KEY}"
  bucket: "${MINIO_BUCKET}"
  use_ssl: false

upload:
  max_size: 524288000
  allowed_types:
    - ".mp4"
    - ".avi"
    - ".mov"
    - ".mkv"
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".gif"
    - ".mp3"
    - ".wav"
    - ".zip"
    - ".rar"
    - ".7z"
  upload_dir: "uploads"

database:
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  name: "${DB_NAME}"